jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8081
   servlet:
      context-path: /domi-api
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://mysql-server:3306/domidb
      username: root
      password: p@ssw0rd1
      hikari:
         poolName: pool

logging:
   level:
      org:
         springframework:
            jdbc:
               core: TRACE
